export { default as AdmminLayout } from './AdminLayout'
export { default as Dashboard } from './Dashboard'
export { default as ManageUser } from './ManageUser'
export { default as MangeClaimOrder } from './MangeClaimOrder'
export { default as ManageOrder } from './ManageOrder'
export { default as AdminMessage } from './AdminMessage'